In [1]:
from __future__ import print_function
import torch

In [2]:
x1 = torch.empty(5, 3)
print(x1)

tensor([[9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 8.4490e-39],
        [1.0286e-38, 9.6429e-39, 8.4490e-39]])


In [3]:
x2 = torch.rand(5, 3)
print(x2)

tensor([[0.6183, 0.5105, 0.1296],
        [0.3015, 0.5792, 0.5460],
        [0.4745, 0.8835, 0.3613],
        [0.4690, 0.5466, 0.9138],
        [0.1711, 0.2004, 0.0244]])


In [4]:
print(x1+x2)

tensor([[0.6183, 0.5105, 0.1296],
        [0.3015, 0.5792, 0.5460],
        [0.4745, 0.8835, 0.3613],
        [0.4690, 0.5466, 0.9138],
        [0.1711, 0.2004, 0.0244]])
